import { Step } from '@/types';

export const steps: Step[] = [
    {
        name: 'User Information',
        fields: ['firstname', 'lastname', 'email', 'phoneNumber', 'password', 'confirmPassword'],
    },
    { name: 'Address', fields: ['address', 'city', 'state', 'zipCode'] },
    { name: 'Personal Details', fields: ['dateOfBirth', 'gender'] },
];

export const cities: string[] = [
    'Agra',
    'Ahmedabad',
    'Ajmer',
    'Akola',
    'Aligarh',
    'Allahabad',
    'Amravati',
    'Amritsar',
    'Aurangabad',
    'Bareilly',
    'Belgaum',
    'Bengaluru',
    'Bhilai',
    'Bhiwandi',
    'Bhopal',
    'Bhubaneswar',
    'Bikaner',
    'Bokaro Steel City',
    'Chandigarh',
    'Chennai',
    'Coimbatore',
    'Cuttack',
    'Davanagere',
    'Dehradun',
    'Delhi',
    'Dhanbad',
    'Durgapur',
    'Faridabad',
    'Firozabad',
    'Ghaziabad',
    'Gopalpur',
    'Gulbarga',
    'Guntur',
    'Gurgaon',
    'Guwahati',
    'Gwalior',
    'Hubli-Dharwad',
    'Howrah',
    'Hyderabad',
    'Indore',
    'Jabalpur',
    'Jaipur',
    'Jalandhar',
    'Jammu',
    'Jamnagar',
    'Jamshedpur',
    'Jhansi',
    'Jodhpur',
    'Kalyan-Dombivli',
    'Kanpur',
    'Kochi',
    'Kolhapur',
    'Kolkata',
    'Kota',
    'Kozhikode',
    'Kurnool',
    'Loni',
    'Lucknow',
    'Ludhiana',
    'Madurai',
    'Maheshtala',
    'Malegaon',
    'Mangalore',
    'Meerut',
    'Moradabad',
    'Mumbai',
    'Mysore',
    'Nagpur',
    'Nanded',
    'Nashik',
    'Navi Mumbai',
    'Noida',
    'Patiala',
    'Patna',
    'Pimpri-Chinchwad',
    'Pune',
    'Raipur',
    'Rajkot',
    'Rajpur Sonarpur',
    'Ranchi',
    'Rourkela',
    'Salem',
    'Saharanpur',
    'Sangli-Miraj & Kupwad',
    'Siliguri',
    'Solapur',
    'South Dumdum',
    'Srinagar',
    'Surat',
    'Thane',
    'Thiruvananthapuram',
    'Tiruchirappalli',
    'Tirunelveli',
    'Tiruppur',
    'Ulhasnagar',
    'Udaipur',
    'Ujjain',
    'Vadodara',
    'Varanasi',
    'Vasai-Virar',
    'Vijayawada',
    'Visakhapatnam',
    'Warangal',
];

export const states: string[] = [
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
    'Andaman and Nicobar Islands',
    'Chandigarh',
    'Dadra and Nagar Haveli and Daman and Diu',
    'Delhi',
    'Lakshadweep',
    'Puducherry',
    'Ladakh',
    'Jammu and Kashmir',
];
